version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    ports: [ '3307:3307' ]
    networks:
      - all-network
  php:
    build: ./docker/php
    ports: [ '9000:9000' ]
    volumes: [ './symfony/:/var/www/symfony:cached' ]
    networks:
      - all-network
  user-nginx:
    container_name: "user-nginx"
    build: ./docker/nginx
    ports: [ '7010:80' ]
    volumes: [ './symfony/:/var/www/symfony:cached' ]
    networks:
      - all-network
networks:
  all-network:
    driver: bridge
