version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3308:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    build: docker/php
    ports: ['9002:9000']
    volumes: ['./symfony/:/var/www/symfony:cached']
  nginx:
    build: docker/nginx
    ports: ['7002:80']
    volumes: ['./symfony/:/var/www/symfony:cached']
