version: '3.7'
services:
  vue-annonce:
    build: ./annonce-microservice
    ports: ['8080:8080']
    volumes: ['./annonce-microservice:/vue-annonce']
  vue-user:
    build: ./user-microservice
    ports: ['8081:8080']
    volumes: ['./user-microservice:/vue-annonce']
  vue-paiement:
    build: ./paiement-microservice
    ports: ['8082:8080']
    volumes: ['./paiement-microservice:/vue-annonce']
